### PR TITLE
Readme edits

### PR DESCRIPTION
**Pull request by dunbam01**
Please review

### CODE REVIEW

**Comment by dunbam01** [comment]
@Tracker619  please review this

**Comment by Tracker619** [comment]
I see these changes to your readme.

**Comment by dunbam01** [comment]
Cool…  it worked.

**Comment by dunbam01** [comment]
Can you fix the conflicts?

Sent from my iPhone

On Apr 5, 2017, at 5:55 PM, "Tracker619" <notifications@github.com<mailto:notifications@github.com>> wrote:


I see these changes to your readme.

**Comment by dunbam01** [comment]
From: steezefamily@googlegroups.com [mailto:steezefamily@googlegroups.com] On Behalf Of Eveline Dunbar
Sent: Thursday, February 14, 2013 11:00 AM
To: steezefamily@googlegroups.com; Dolores Truskowski <cdtruskowski@optonline.net>; Edie <ronedi@verizon.net>; Sandi <kcsing@juno.com>; Nancy Leclair <NALA52359@mygsc.com>; Dorothy <HDSPRIGGS@aol.com>; Arlene <arlened315@yahoo.com>; Bob Wood <bobwood@gmavt.net>; Theresa Szkotak <theresaszkotak@hotmail.com>
Subject: pictures

Valentine pictures. I think i forgot to send them. took them this morning!
Evie
--
You received this message because you are subscribed to the Google Groups "Family" group.
To unsubscribe from this group and stop receiving emails from it, send an email to steezefamily+unsubscribe@googlegroups.com<mailto:steezefamily+unsubscribe@googlegroups.com>.
For more options, visit https://groups.google.com/groups/opt_out.

**Comment by Tracker619** [comment]
:?

**Comment by dunbam01** [comment]
I don't know what this is. Must be a mistake for me cleaning out all my emails!!  Please delete it permanently. Thanks

Sent from my iPhone

On Sep 19, 2017, at 2:55 PM, "MikeF" <notifications@github.com<mailto:notifications@github.com>> wrote:

:?

**Pull request closed without merging**
